# Welcome to Jupyter!

In [1]:
my_list = []

for val in range(1,100):
    if val%2==0:
        my_list.append(val)

# my_list        

In [2]:
# Using list comprehension

my_list = [number for number in range(1,100) if number%2==0]
#my_list

In [3]:
import numpy as np

# Creating Arrays

In [4]:
my_list = [1,2,3]
new_array = np.array(my_list)
new_array

array([1, 2, 3])

# Creating a 2d Matrix

In [5]:
# You need to pass in a list of lists

new_matrix = np.array([[1,2,3],[4,5,6]])
new_matrix

array([[1, 2, 3],
       [4, 5, 6]])

# Getting the Dimensions

In [6]:
new_matrix.shape

(2, 3)

# Creating evenly spaced data

In [7]:
# It's a-range not ar-range
new_array = np.arange(0,30,2)
new_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# Reshaping an array to a matrix

In [8]:
new_array = new_array.reshape(3,5)
new_array

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

# A function similar to arange (linspace)

In [9]:
# Just tell it how many numbers you want and it will split up the interval

new_array = np.linspace(0,4,9)
new_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

# Changing the dimensions in place

In [10]:
new_array.resize(3,3)
new_array

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

# Creating a a matrix of zeroes and ones. Notice the extra bracket

In [11]:
ones_matrix = np.ones((5,5))
ones_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
zero_matrix = np.zeros((5,5))
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# Array of Repeated Values

In [15]:
# Pass repeated lists
new_array = [[1,2,3]*3]
new_array

[[1, 2, 3, 1, 2, 3, 1, 2, 3]]

# Numpy's Repeat Function

In [16]:
# Notice the sequence of repetitions

new_array = np.repeat([1,2,3], 3)
new_array

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Vertical Stacking

In [17]:
# Create an array of integers (1)

p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
# Vertically stack the 2 arrays (p and 2*p)

new_array = np.vstack([p,2*p])
new_array

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

# Horizontal Stacking

In [19]:
# Horizontally stack the 2 arrays (p and 2*p)

new_array = np.hstack([p,2*p])
new_array

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Element wise arithmetic and Dot Products

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print (a + b)
print (a*b)
print (a*2)
print (np.dot(a,b))

[5 7 9]
[ 4 10 18]
[2 4 6]
32


# Element wise square

In [21]:
new_array = np.vstack([a,a**2])
new_array

array([[1, 2, 3],
       [1, 4, 9]])

# Recall the Shape operator

In [22]:
new_array.shape

(2, 3)

# Transpose of a matrix

In [23]:
new_array.T

array([[1, 1],
       [2, 4],
       [3, 9]])

# Checking the data type of array using dtype

In [24]:
new_array.dtype

dtype('int64')

# Casting an array to Desired Type using astype

In [25]:
new_array = new_array.astype('f')
new_array.dtype

dtype('float32')

In [26]:
a = np.array([-4,-2,1,3,5])

In [27]:
# Useful Mathematical functions

In [28]:
a.sum()

3

In [29]:
a.max()

5

In [30]:
a.min()

-4

In [31]:
a.mean()

0.6

In [32]:
a.std()

3.2619012860600183

In [33]:
# Finding the index of maximum and minimum Values

In [34]:
a.argmax()

4

In [35]:
a.argmin()

0

# Indexing and Slicing

In [36]:
# Let's create an array with square of numbers from 0 to 12

a = np.arange(13)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [37]:
# Accessing an element

a[0], a[:5]

(0, array([ 0,  1,  4,  9, 16]))

### Slicing last 4 elements

In [38]:
a[-4:]

array([ 81, 100, 121, 144])

#### Let's see what happens for 2d Arrays

In [39]:
a = np.arange(36)
a.resize((6,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### Accessing an element, use comma notification (Indexing starts from zero)

In [40]:
a[2,3]

15

In [41]:
a[0,0]

0

### Colon notation to select certain rows and columns

In [42]:
a[3,3]

21

In [43]:
# Returns the column numbers 3 to 6 of the row number 3.
# Note that arr[3,6] doesn't exist, but it gives no error.

a[3, 3:6]

array([21, 22, 23])

### Excluding a column in slicing

In [44]:
# Excludes the last column

a[0,:-1]

array([0, 1, 2, 3, 4])

### Skipping over some elemnts.

In [45]:
# Skips every 2nd element of the last row
a[-1, ::2]

array([30, 32, 34])

### Conditional indexing and assignment

In [46]:
a[a>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

### Repalcing multiple elements with same type

In [47]:
a[a>30] = 30
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Slicing a submatrix

In [48]:
x = a[:3,:3]
x

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

 # In slicing, always put the length as  the last parameter

### Initialization of matrix

In [49]:
x[:] = 0
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Let's see the original array

In [50]:
a

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Notice that modifying a slice also modifies the original array

# Copying ararys in numpy

In [51]:
a_copy = a.copy()
a

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Now let's see if changes are reflected back

In [52]:
a_copy[:] = 10
print(a_copy)
print()
print(a)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [53]:
for row in a:
    print(row)

[0 0 0 3 4 5]
[ 0  0  0  9 10 11]
[ 0  0  0 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 30 30 30 30 30]


In [54]:
for i in range(len(a)):
    print(a[i])

[0 0 0 3 4 5]
[ 0  0  0  9 10 11]
[ 0  0  0 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 30 30 30 30 30]


# Enumerate

In [55]:
for i, row in enumerate(a):
    print('row', i,'is',row)

row 0 is [0 0 0 3 4 5]
row 1 is [ 0  0  0  9 10 11]
row 2 is [ 0  0  0 15 16 17]
row 3 is [18 19 20 21 22 23]
row 4 is [24 25 26 27 28 29]
row 5 is [30 30 30 30 30 30]


In [56]:
a_2 = a**2
a_2

array([[  0,   0,   0,   9,  16,  25],
       [  0,   0,   0,  81, 100, 121],
       [  0,   0,   0, 225, 256, 289],
       [324, 361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784, 841],
       [900, 900, 900, 900, 900, 900]])

# Zipping (Iterating simultaneously

In [57]:
for i, j in zip(a, a_2):
    print(i, '+', j, '=', i+j)

[0 0 0 3 4 5] + [ 0  0  0  9 16 25] = [ 0  0  0 12 20 30]
[ 0  0  0  9 10 11] + [  0   0   0  81 100 121] = [  0   0   0  90 110 132]
[ 0  0  0 15 16 17] + [  0   0   0 225 256 289] = [  0   0   0 240 272 306]
[18 19 20 21 22 23] + [324 361 400 441 484 529] = [342 380 420 462 506 552]
[24 25 26 27 28 29] + [576 625 676 729 784 841] = [600 650 702 756 812 870]
[30 30 30 30 30 30] + [900 900 900 900 900 900] = [930 930 930 930 930 930]


This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook